# fly.toml app configuration file generated for maine-coon on 2023-11-13T04:36:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maine-coon"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder-jammy-base:0.4.252"
  [build.args]
    BPE_APPEND_JAVA_TOOL_OPTIONS = "-XX:ReservedCodeCacheSize=30M -Xss256k"
    BPE_BPL_JVM_THREAD_COUNT = "10"
    BPE_DELIM_JAVA_TOOL_OPTIONS = " "
    BPE_SERVER_TOMCAT_THREADS_MAX = "2"
    BP_JVM_VERSION = "21"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[metrics]
port = 8080
path = "/actuator/prometheus"
